# Import library
```{r}
library(dplyr)
library(stringr)
library(rvest)
library(purrr)
library(tidyr)
library(vroom)
library(DBI)
library(RSQLite)
```

# Read web page
```{r}
url <- "https://fbref.com/en/country/clubs/ENG/England-Football-Clubs"

# Send a GET request to the URL and read the HTML content
page <- read_html(url)
```

# Get all the team from Premier league
```{r}
team_id <- page %>%
  html_elements("th.left[data-stat='team'] a") %>%
  html_attr("href") %>%
  str_sub(12, 19)

teams <- page %>% 
  html_element("table") %>%
  html_table() %>% 
  mutate(Id = team_id) %>% 
  select(Id, 
         Squad,
         Gender,
         Comp,
         Other_Names = `Other Names`) %>% 
  filter((Comp != "" |
            Squad %in% c("Burnley FC", "Leeds United FC", "Sunderland AFC")),
         Comp != "Premier League 2") %>% 
  mutate(Comp = if_else(Squad %in% c("Burnley FC", "Leeds United FC", "Sunderland AFC"),
                        "Premier League",
                        Comp),
         Other_Names = Squad %>%
           str_remove("\\b(FC|AFC |AFC)\\b")%>%
           str_trim(side = "right"))
```

# Get the location of stadium
```{r}
df_stadium <- vroom("English_stadiums.csv") 

df_stadium <- df_stadium %>% 
  mutate(clubLabel = str_replace_all(clubLabel, "\\.", "") %>%
           str_remove("\\b(FC|AFC )\\b") %>%  # Adjusted to match the pattern without dots
           str_trim(side = "right")) %>% 
  rename(Other_Names = clubLabel,
         Venue_Name = venueLabel)
```

```{r}
teams <- teams %>% 
  left_join(df_stadium, by="Other_Names")
```
```{r}
abv <- c("BOU", "ARS", "AVL", "BRE", "BHA", "BUR", "CHE", "CRY", "EVE", "FUL", "LEE", "LIV", "MCI", "MUN", "NEW", "NFO", "SUN", "TOT", "WHU", "WOL")

opta_name <- c("Arsenal", "Aston Villa", "Bournemouth", "Brentford", "Brighton",
        "Burnley", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Leeds",
        "Liverpool", "Man City", "Man Utd", "Newcastle",
        "Nottm Forest", "Sunderland", "Tottenham", "West Ham", "Wolves")

color <- c("#DA291C", "#EF0107","#95BFE5","#E4010B","#0057B8","#6E1142","#1B458F","#003399","#F0F0F0","#0A3A89","#FCE11A","#C8102E","#6CABDD","#DA291C","#241F20","#DD0000","#EE1E2D","#132257","#7A263A","#FDB913")

pl_team <- teams %>% 
  filter(Comp == 'Premier League') %>% 
  select(Id) %>% 
  mutate(Abv = abv,
         Opta_Name = opta_name,
         Color = color)

teams <- teams %>% 
  left_join(pl_team, by="Id")
```

# Write the table in a database

```{r}
# Define the name of the SQLite database file
sqlite_file <- "my_database.db"

# Connect to the SQLite database
con <- dbConnect(RSQLite::SQLite(), dbname = sqlite_file)

# Drop the table if it already exists
dbExecute(con, "DROP TABLE IF EXISTS Table_teams;")

# Write the DataFrame to the SQLite database as a table
dbWriteTable(con, "Table_teams", teams, overwrite = TRUE, row.names = FALSE)

# Close the database connection
dbDisconnect(con)
```

