name: Deploy ML Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update code on Raspberry Pi
        run: |
          cd /home/pi/Prono_PL
          git fetch --all
          git pull --ff-only
          echo "Code mis à jour avec succès !"
